#!/bin/sh

# A nice project which explains each package detail: 
# https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json
# this project forked to:
# https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
# the forked project cloned locally (for backup in any case) (project_github_full_list.json).

# In this script "Wallpaper changer" application is removing too. But you can set the wallpaper from "gallery" app.

# if any app or case not working, see all the logs with that command: "adb logcat"

# re-install any app: 
# adb shell cmd package install-existing com.packageid

# list of installed applicaitons:
# adb shell cmd package list packages

# Do not remove:
# - "SIM Menu" --> allow some banking apps to send you notification without SMS.
# - com.google.android.gsf + com.google.android.gms package --> needs only on "whatsapp" or "signal" only "mobile phone verification" screen.
# - com.huawei.systemmanager -> It can make an app not working in background.
# - com.android.pacprocessor -> stands for proxy auto-config, and this file defines how web browsers and other agents can automatically define the correct proxy server for fetching an URL.
# - com.android.dreams -> screensavers
# - com.android.providers.blockednumber -> "recent apps" feature does not work properly.

adb --help || exit

echo "adb is in your path"

adb shell 'pm uninstall --user 0 com.google.android.youtube'

echo "first command finished with success."

# huawei
adb shell 'pm uninstall --user 0 com.huawei.android.FloatTasks' # Floating dock function. https://consumer.huawei.com/en/support/how-to/detail-troubleshooting/en-us00310067/
adb shell 'pm uninstall --user 0 com.huawei.android.chr'
adb shell 'pm uninstall --user 0 com.huawei.android.hsf'
adb shell 'pm uninstall --user 0 com.huawei.android.karaoke'
adb shell 'pm uninstall --user 0 com.android.partnerbrowsercustomizations.tmobile'
adb shell 'pm uninstall --user 0 com.huawei.hwid'
adb shell 'pm uninstall --user 0 com.huawei.iaware'
adb shell 'pm uninstall --user 0 com.huawei.parentcontrol'
adb shell 'pm uninstall --user 0 com.huawei.synergy'
adb shell 'pm uninstall --user 0 com.android.apps.tag'
adb shell 'pm uninstall --user 0 com.android.bluetoothmidiservice'
adb shell 'pm uninstall --user 0 com.android.printspooler' # printer problems. But I don't use it.
adb shell 'pm uninstall --user 0 com.android.keyguard'
adb shell 'pm uninstall --user 0 com.huawei.trustagent'
adb shell 'pm uninstall --user 0 com.android.dreams.basic'
adb shell 'pm uninstall --user 0 com.huawei.vassistant'        # HiVoice app
adb shell 'pm uninstall --user 0 com.huawei.HwMultiScreenShot' # screenshot with scroll
adb shell 'pm uninstall --user 0 com.hisi.mapcon'              # "wi-fi calling" feature
adb shell 'pm uninstall --user 0 com.google.android.setupwizard'
adb shell 'pm uninstall --user 0 com.android.providers.partnerbookmarks'
adb shell 'pm uninstall --user 0 com.android.backupconfirm'
adb shell 'pm uninstall --user 0 com.huawei.contacts.sync'
adb shell 'pm uninstall --user 0 com.android.calllogbackup'
adb shell 'pm uninstall --user 0 com.android.calendar' # Instead of this, use "simple calendar" app
adb shell 'pm uninstall --user 0 com.huawei.android.pushagent'
adb shell 'pm uninstall --user 0 com.huawei.android.wfdft'
adb shell 'pm uninstall --user 0 com.huawei.android.mirrorshare'
adb shell 'pm uninstall --user 0 com.huawei.mirrorlink'
adb shell 'pm uninstall --user 0 com.huawei.bd'
adb shell 'pm uninstall --user 0 com.google.android.gsf'
adb shell 'pm uninstall --user 0 com.huawei.hwasm'
adb shell 'pm uninstall --user 0 com.ironsource.appcloud.oobe.huawei'
adb shell 'pm uninstall --user 0 com.huawei.desktop.explorer'
adb shell 'pm uninstall --user 0 com.huawei.hidisk'
adb shell 'pm uninstall --user 0 com.huawei.android.thememanager'
adb shell 'pm uninstall --user 0 com.huawei.appmarket'
adb shell 'pm uninstall --user 0 com.swiftkey.swiftkeyconfigurator'
adb shell 'pm uninstall --user 0 com.huawei.hitouch'
adb shell 'pm uninstall --user 0 com.huawei.livewallpaper.flowersbloom'
adb shell 'pm uninstall --user 0 com.huawei.pcassistant'
adb shell 'pm uninstall --user 0 com.huawei.livewallpaper.naturalgarden'
adb shell 'pm uninstall --user 0 com.huawei.android.instantshare'
adb shell 'pm uninstall --user 0 com.huawei.livewallpaper.artflower'
adb shell 'pm uninstall --user 0 com.huawei.securitymgr'
adb shell 'pm uninstall --user 0 com.huawei.livewallpaper.ripplestone'
adb shell 'pm uninstall --user 0 com.realvnc.android.remote'
adb shell 'pm uninstall --user 0 com.huawei.wallet'
adb shell 'pm uninstall --user 0 com.huawei.search' # search apps on launcher
adb shell 'pm uninstall --user 0 com.huawei.hifolder'
adb shell 'pm uninstall --user 0 com.huawei.himovie.overseas'
adb shell 'pm uninstall --user 0 com.huawei.android.remotecontroller'
adb shell 'pm uninstall --user 0 com.huawei.hwdetectrepair'
adb shell 'pm uninstall --user 0 com.huawei.tips'
adb shell 'pm uninstall --user 0 com.huawei.android.tips'
adb shell 'pm uninstall --user 0 com.hicloud.android.clone'
adb shell 'pm uninstall --user 0 com.android.mediacenter'
adb shell 'pm uninstall --user 0 com.android.hwmirror' # Huawei Mirror app.
adb shell 'pm uninstall --user 0 com.instagram.android'
adb shell 'pm uninstall --user 0 com.microsoft.translator'
adb shell 'pm uninstall --user 0 com.huawei.health'
adb shell 'pm uninstall --user 0 com.facebook.katana'
adb shell 'pm uninstall --user 0 com.google.android.apps.docs.editors.slides'
adb shell 'pm uninstall --user 0 com.google.android.apps.docs.editors.sheets'
adb shell 'pm uninstall --user 0 com.google.android.apps.docs.editors.docs'
adb shell 'pm uninstall --user 0 com.huawei.compass'
adb shell 'pm uninstall --user 0 com.booking'
adb shell 'pm uninstall --user 0 com.android.egg'
adb shell 'pm uninstall --user 0 com.huawei.KoBackup'
adb shell 'pm uninstall --user 0 com.huawei.android.totemweather'
adb shell 'pm uninstall --user 0 com.google.android.marvin.talkback'
adb shell 'pm uninstall --user 0 com.android.hotwordenrollment.xgoogle'
adb shell 'pm uninstall --user 0 com.facebook.services'
adb shell 'pm uninstall --user 0 com.google.android.music'
adb shell 'pm uninstall --user 0 com.google.android.apps.work.oobconfig'
adb shell 'pm uninstall --user 0 com.google.android.gm'
adb shell 'pm uninstall --user 0 com.google.android.apps.tachyon'
adb shell 'pm uninstall --user 0 com.google.android.googlequicksearchbox'
adb shell 'pm uninstall --user 0 com.google.android.onetimeinitializer'
adb shell 'pm uninstall --user 0 com.huawei.phoneservice' # HiCare app.
adb shell 'pm uninstall --user 0 com.android.vending'     # Google Play Store app.
adb shell 'pm uninstall --user 0 com.huawei.gameassistant'
adb shell 'pm uninstall --user 0 com.android.hotwordenrollment.okgoogle'
adb shell 'pm uninstall --user 0 com.google.android.apps.docs'
adb shell 'pm uninstall --user 0 com.google.android.apps.maps'
adb shell 'pm uninstall --user 0 com.google.android.syncadapters.contacts'
adb shell 'pm uninstall --user 0 com.example.android.notepad'
adb shell 'pm uninstall --user 0 com.android.chrome'
adb shell 'pm uninstall --user 0 com.huawei.watch.sync'
adb shell 'pm uninstall --user 0 com.google.android.tts'
adb shell 'pm uninstall --user 0 com.google.android.partnersetup'
adb shell 'pm uninstall --user 0 com.huawei.fido.uafclient'
adb shell 'pm uninstall --user 0 com.google.android.videos'
adb shell 'pm uninstall --user 0 com.huawei.contactscamcard'
adb shell 'pm uninstall --user 0 com.google.android.feedback'
adb shell 'pm uninstall --user 0 com.google.android.printservice.recommendation'
adb shell 'pm uninstall --user 0 com.google.android.apps.photos'
adb shell 'pm uninstall --user 0 com.google.android.syncadapters.calendar'
adb shell 'pm uninstall --user 0 com.huawei.android.totemweatherwidget'
adb shell 'pm uninstall --user 0 com.android.dreams.phototable'
adb shell 'pm uninstall --user 0 com.facebook.system'
adb shell 'pm uninstall --user 0 com.google.android.backuptransport'
adb shell 'pm uninstall --user 0 com.android.bookmarkprovider'
adb shell 'pm uninstall --user 0 com.huawei.android.totemweatherapp'
adb shell 'pm uninstall --user 0 com.huawei.livewallpaper.mountaincloud'
adb shell 'pm uninstall --user 0 com.android.email'
adb shell 'pm uninstall --user 0 com.facebook.appmanager'
adb shell 'pm uninstall --user 0 com.android.managedprovisioning'

# oppo
adb shell 'pm uninstall --user 0 com.oppo.sos'
adb shell 'pm uninstall --user 0 com.google.android.apps.wellbeing'
adb shell 'pm uninstall --user 0 com.oplus.crashbox'
adb shell 'pm uninstall --user 0 com.coloros.gamespace'
adb shell 'pm uninstall --user 0 com.nearme.romupdate'
adb shell 'pm uninstall --user 0 com.nearme.statistics.rom'
adb shell 'pm uninstall --user 0 com.coloros.sau'
adb shell 'pm uninstall --user 0 com.oplus.onetrace'
adb shell 'pm uninstall --user 0 com.coloros.childrenspace'
adb shell 'pm uninstall --user 0 com.coloros.exserviceui'
adb shell 'pm uninstall --user 0 com.coloros.healthcheck'
adb shell 'pm uninstall --user 0 com.coloros.healthservice'
adb shell 'pm uninstall --user 0 com.google.android.keep'
adb shell 'pm uninstall --user 0 com.google.android.gms.location.history'
adb shell 'pm uninstall --user 0 com.google.mainline.telemetry'
adb shell 'pm uninstall --user 0 com.coloros.smartsidebar'
adb shell 'pm uninstall --user 0 com.coloros.smartdrive'
adb shell 'pm uninstall --user 0 com.oppo.operationManual'
adb shell 'pm uninstall --user 0 com.oppoex.afterservice'
adb shell 'pm uninstall --user 0 com.oppo.atlas'
adb shell 'pm uninstall --user 0 com.oppo.usercenter'
adb shell 'pm uninstall --user 0 com.coloros.sceneservice'
adb shell 'pm uninstall --user 0 com.coloros.uxdesign'
adb shell 'pm uninstall --user 0 com.coloros.focusmode'
adb shell 'pm uninstall --user 0 com.coloros.securepay'
adb shell 'pm uninstall --user 0 com.coloros.eyeprotect'
adb shell 'pm uninstall --user 0 com.coloros.activation'
adb shell 'pm uninstall --user 0 com.coloros.floatassistant'
adb shell 'pm uninstall --user 0 com.google.android.projection.gearhead'
adb shell 'pm uninstall --user 0 com.google.android.calendar'
adb shell 'pm uninstall --user 0 com.heytap.music'
adb shell 'pm uninstall --user 0 com.coloros.video'
adb shell 'pm uninstall --user 0 com.coloros.gesture'
adb shell 'pm uninstall --user 0 com.google.android.gms'

# samsung
adb shell 'pm uninstall --user 0 android.autoinstalls.config.samsung'
adb shell 'pm uninstall --user 0 com.amazon.appmanager'
adb shell 'pm uninstall --user 0 com.android.bluetoothmidiservice'
adb shell 'pm uninstall --user 0 com.android.calllogbackup'
adb shell 'pm uninstall --user 0 com.android.chrome'
adb shell 'pm uninstall --user 0 com.android.dreams.phototable'
adb shell 'pm uninstall --user 0 com.android.egg'
adb shell 'pm uninstall --user 0 com.android.providers.partnerbookmarks'
adb shell 'pm uninstall --user 0 com.android.traceur'
adb shell 'pm uninstall --user 0 com.diotek.sec.lookup.dictionary'
adb shell 'pm uninstall --user 0 com.facebook.appmanager'
adb shell 'pm uninstall --user 0 com.facebook.services'
adb shell 'pm uninstall --user 0 com.facebook.system'
adb shell 'pm uninstall --user 0 com.google.android.apps.maps'
adb shell 'pm uninstall --user 0 com.google.android.apps.messaging'
adb shell 'pm uninstall --user 0 com.google.android.apps.restore'
adb shell 'pm uninstall --user 0 com.google.android.apps.tachyon'
adb shell 'pm uninstall --user 0 com.google.android.as'
adb shell 'pm uninstall --user 0 com.google.android.feedback'
adb shell 'pm uninstall --user 0 com.google.android.gm'
adb shell 'pm uninstall --user 0 com.google.android.gms.location.history'
adb shell 'pm uninstall --user 0 com.google.android.googlequicksearchbox'
adb shell 'pm uninstall --user 0 com.google.android.onetimeinitializer'
adb shell 'pm uninstall --user 0 com.google.android.partnersetup'
adb shell 'pm uninstall --user 0 com.google.android.printservice.recommendation'
adb shell 'pm uninstall --user 0 com.google.android.projection.gearhead'
adb shell 'pm uninstall --user 0 com.google.android.tts'
adb shell 'pm uninstall --user 0 com.google.android.youtube'
adb shell 'pm uninstall --user 0 com.google.ar.core'
adb shell 'pm uninstall --user 0 com.google.audio.hearing.visualization.accessibility.scribe'
adb shell 'pm uninstall --user 0 com.hiya.star'
adb shell 'pm uninstall --user 0 com.knox.vpn.proxyhandler'
adb shell 'pm uninstall --user 0 com.microsoft.appmanager'
adb shell 'pm uninstall --user 0 com.microsoft.skydrive'
adb shell 'pm uninstall --user 0 com.monotype.android.font.foundation'
adb shell 'pm uninstall --user 0 com.monotype.android.font.samsungone'
adb shell 'pm uninstall --user 0 com.samsung.aasaservice'
adb shell 'pm uninstall --user 0 com.samsung.android.aircommandmanager'
adb shell 'pm uninstall --user 0 com.samsung.android.allshare.service.mediashare'
adb shell 'pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload'
adb shell 'pm uninstall --user 0 com.samsung.android.app.clipboardedge'
adb shell 'pm uninstall --user 0 com.samsung.android.app.cocktailbarservice'
adb shell 'pm uninstall --user 0 com.samsung.android.app.omcagent'
adb shell 'pm uninstall --user 0 com.samsung.android.app.reminder'
adb shell 'pm uninstall --user 0 com.samsung.android.app.settings.bixby'
adb shell 'pm uninstall --user 0 com.samsung.android.app.spage'
adb shell 'pm uninstall --user 0 com.samsung.android.app.taskedge'
adb shell 'pm uninstall --user 0 com.samsung.android.app.watchmanagerstub'
adb shell 'pm uninstall --user 0 com.samsung.android.ardrawing'
adb shell 'pm uninstall --user 0 com.samsung.android.aremoji'
adb shell 'pm uninstall --user 0 com.samsung.android.aremojieditor'
adb shell 'pm uninstall --user 0 com.samsung.android.arzone'
adb shell 'pm uninstall --user 0 com.samsung.android.authfw'
adb shell 'pm uninstall --user 0 com.samsung.android.aware.service'
adb shell 'pm uninstall --user 0 com.samsung.android.bbc.bbcagent'
adb shell 'pm uninstall --user 0 com.samsung.android.beaconmanager'
adb shell 'pm uninstall --user 0 com.samsung.android.bixbyvision.framework'
adb shell 'pm uninstall --user 0 com.samsung.android.da.daagent'
adb shell 'pm uninstall --user 0 com.samsung.android.dqagent'
adb shell 'pm uninstall --user 0 com.samsung.android.dynamiclock'
adb shell 'pm uninstall --user 0 com.samsung.android.easysetup'
adb shell 'pm uninstall --user 0 com.samsung.android.fmm'
adb shell 'pm uninstall --user 0 com.samsung.android.forest'
adb shell 'pm uninstall --user 0 com.samsung.android.game.gamehome'
adb shell 'pm uninstall --user 0 com.samsung.android.game.gametools'
adb shell 'pm uninstall --user 0 com.samsung.android.game.gos'
adb shell 'pm uninstall --user 0 com.samsung.android.ipsgeofence'
adb shell 'pm uninstall --user 0 com.samsung.android.kidsinstaller'
adb shell 'pm uninstall --user 0 com.samsung.android.knox.analytics.uploader'
adb shell 'pm uninstall --user 0 com.samsung.android.knox.attestation'
adb shell 'pm uninstall --user 0 com.samsung.android.knox.containeragent'
adb shell 'pm uninstall --user 0 com.samsung.android.knox.containercore'
adb shell 'pm uninstall --user 0 com.samsung.android.knox.pushmanager'
adb shell 'pm uninstall --user 0 com.samsung.android.livestickers'
adb shell 'pm uninstall --user 0 com.samsung.android.mateagent'
adb shell 'pm uninstall --user 0 com.samsung.android.mdecservice'
adb shell 'pm uninstall --user 0 com.samsung.android.mdm'
adb shell 'pm uninstall --user 0 com.samsung.android.mdx'
adb shell 'pm uninstall --user 0 com.samsung.android.mdx.kit'
adb shell 'pm uninstall --user 0 com.samsung.android.mobileservice'
adb shell 'pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider'
adb shell 'pm uninstall --user 0 com.samsung.android.networkdiagnostic'
adb shell 'pm uninstall --user 0 com.samsung.android.rubin.app'
adb shell 'pm uninstall --user 0 com.samsung.android.samsungpass'
adb shell 'pm uninstall --user 0 com.samsung.android.samsungpassautofill'
adb shell 'pm uninstall --user 0 com.samsung.android.samsungpositioning'
adb shell 'pm uninstall --user 0 com.samsung.android.scloud'
adb shell 'pm uninstall --user 0 com.samsung.android.sdk.handwriting'
adb shell 'pm uninstall --user 0 com.samsung.android.sdm.config'
adb shell 'pm uninstall --user 0 com.samsung.android.service.peoplestripe'
adb shell 'pm uninstall --user 0 com.samsung.android.shortcutbackupservice'
adb shell 'pm uninstall --user 0 com.samsung.android.smartcallprovider'
adb shell 'pm uninstall --user 0 com.samsung.android.smartswitchassistant'
adb shell 'pm uninstall --user 0 com.samsung.android.spayfw'
adb shell 'pm uninstall --user 0 com.samsung.android.stickercenter'
adb shell 'pm uninstall --user 0 com.samsung.android.svcagent'
adb shell 'pm uninstall --user 0 com.samsung.android.visionintelligence'
adb shell 'pm uninstall --user 0 com.samsung.android.wifi.softap.resources'
adb shell 'pm uninstall --user 0 com.samsung.crane'
adb shell 'pm uninstall --user 0 com.samsung.faceservice'
adb shell 'pm uninstall --user 0 com.samsung.ipservice'
adb shell 'pm uninstall --user 0 com.samsung.klmsagent'
adb shell 'pm uninstall --user 0 com.samsung.knox.securefolder'
adb shell 'pm uninstall --user 0 com.samsung.mlp'
adb shell 'pm uninstall --user 0 com.samsung.rcs'
adb shell 'pm uninstall --user 0 com.samsung.safetyinformation'
adb shell 'pm uninstall --user 0 com.samsung.storyservice'
adb shell 'pm uninstall --user 0 com.sec.android.app.applinker'
adb shell 'pm uninstall --user 0 com.sec.android.app.billing'
adb shell 'pm uninstall --user 0 com.sec.android.app.bluetoothtest'
adb shell 'pm uninstall --user 0 com.sec.android.app.chromecustomizations'
adb shell 'pm uninstall --user 0 com.sec.android.app.DataCreate'
adb shell 'pm uninstall --user 0 com.sec.android.app.factorykeystring'
adb shell 'pm uninstall --user 0 com.sec.android.app.hwmoduletest'
adb shell 'pm uninstall --user 0 com.sec.android.app.magnifier'
adb shell 'pm uninstall --user 0 com.sec.android.app.parser'
adb shell 'pm uninstall --user 0 com.sec.android.app.quicktool'
adb shell 'pm uninstall --user 0 com.sec.android.app.safetyassurance'
adb shell 'pm uninstall --user 0 com.sec.android.app.samsungapps'
adb shell 'pm uninstall --user 0 com.sec.android.app.SecSetupWizard'
adb shell 'pm uninstall --user 0 com.sec.android.app.servicemodeapp'
adb shell 'pm uninstall --user 0 com.sec.android.app.setupwizardlegalprovider'
adb shell 'pm uninstall --user 0 com.sec.android.app.soundalive'
adb shell 'pm uninstall --user 0 com.sec.android.app.wlantest'
adb shell 'pm uninstall --user 0 com.sec.android.daemonapp'
adb shell 'pm uninstall --user 0 com.sec.android.diagmonagent'
adb shell 'pm uninstall --user 0 com.sec.android.easyMover.Agent'
adb shell 'pm uninstall --user 0 com.sec.android.easyonehand'
adb shell 'pm uninstall --user 0 com.sec.android.mimage.avatarstickers'
adb shell 'pm uninstall --user 0 com.sec.android.RilServiceModeApp'
adb shell 'pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget'
adb shell 'pm uninstall --user 0 com.sec.android.widgetapp.webmanual'
adb shell 'pm uninstall --user 0 com.sec.app.RilErrorNotifier'
adb shell 'pm uninstall --user 0 com.sec.bcservice'
adb shell 'pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms'
adb shell 'pm uninstall --user 0 com.sec.enterprise.mdm.services.simpin'
adb shell 'pm uninstall --user 0 com.sec.epdgtestapp'
adb shell 'pm uninstall --user 0 com.sec.factory'
adb shell 'pm uninstall --user 0 com.sec.factory.camera'
adb shell 'pm uninstall --user 0 com.sec.hearingadjust'
adb shell 'pm uninstall --user 0 com.sec.imslogger'
adb shell 'pm uninstall --user 0 com.sec.location.nsflp2'
adb shell 'pm uninstall --user 0 com.sec.modem.settings'
adb shell 'pm uninstall --user 0 com.sec.phone'
adb shell 'pm uninstall --user 0 com.sec.spp.push'
adb shell 'pm uninstall --user 0 com.sec.usbsettings'
adb shell 'pm uninstall --user 0 com.sec.vsim.ericssonnsds.webapp'
adb shell 'pm uninstall --user 0 com.skms.android.agent'
adb shell 'pm uninstall --user 0 com.wsomacp'
adb shell 'pm uninstall --user 0 com.samsung.android.app.routines'
adb shell 'pm uninstall --user 0 com.samsung.android.app.sharelive'
adb shell 'pm uninstall --user 0 com.osp.app.signin'
adb shell 'pm uninstall --user 0 com.samsung.android.lool'
adb shell 'pm uninstall --user 0 com.samsung.android.service.stplatform'
adb shell 'pm uninstall --user 0 com.samsung.android.smartsuggestions'

# keyboards
echo "disable keyboard after install 'openboard' using below command:"
echo adb shell 'pm uninstall --user 0 com.touchtype.swiftkey' # microsoft keyboard
echo adb shell 'pm uninstall --user 0 com.google.android.inputmethod.latin' # google keyboard
echo adb shell 'pm uninstall --user 0 com.samsung.android.honeyboard'
